default_agent: customer_support_agent
agents:
  customer_support_agent:
    name: customer_support_agent
    entrypoint: /home/sagemaker-user/tmp/amazon-bedrock-agentcore-samples/01-tutorials/07-AgentCore-E2E/lab_helpers/lab4_runtime.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::208351349121:role/CustomerSupportAssistantBedrockAgentCoreRole-us-west-2
      execution_role_auto_create: false
      account: '208351349121'
      region: us-west-2
      ecr_repository: 208351349121.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-customer_support_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: customer_support_agent-p55ySX7xxB
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:208351349121:runtime/customer_support_agent-p55ySX7xxB
      agent_session_id: 0beba81b-a650-4bbb-bad7-f5bede13fad8
    codebuild:
      project_name: bedrock-agentcore-customer_support_agent-builder
      execution_role: arn:aws:iam::208351349121:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-aa96c3a063
      source_bucket: bedrock-agentcore-codebuild-sources-208351349121-us-west-2
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - 1nd04m3h95vmh7a0q34cr3l0ed
        discoveryUrl: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_Opao2l9lx/.well-known/openid-configuration
    oauth_configuration: null
