default_agent: lg01
agents:
  lg01:
    name: lg01
    entrypoint: langgraph_agent_web_search.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::266239926753:role/agentcorerole
      account: '266239926753'
      region: us-west-2
      ecr_repository: 266239926753.dkr.ecr.us-west-2.amazonaws.com/bedrock_agentcore-lg01
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
    bedrock_agentcore:
      agent_id: lg01-YxKPUWA2CE
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:266239926753:runtime/lg01-YxKPUWA2CE
      agent_session_id: 7b08230f-2aee-4b3c-89b1-c34e06bd5a93
    authorizer_configuration: null
    oauth_configuration: null
