#!/usr/bin/env bash
# Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Run the demo console: FastAPI on :8000, Vite UI on :5173.
#
# Reads AWS credentials from .env and deployed resource IDs from .env.deploy
# (generated by scripts/write_env.py). Ctrl-C stops both processes.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

for required in .env .env.deploy; do
  if [[ ! -f "$required" ]]; then
    echo "ERROR: $required is missing." >&2
    [[ "$required" == ".env.deploy" ]] &&
      echo "  Run: python3 scripts/write_env.py (after terraform apply)" >&2
    exit 1
  fi
done

set -a
# shellcheck disable=SC1091
source .env
# shellcheck disable=SC1091
source .env.deploy
set +a
# A stale SSO profile would otherwise take precedence over the static keys.
unset AWS_PROFILE

if [[ ! -x .venv/bin/uvicorn ]]; then
  echo "ERROR: .venv is missing. Run ./scripts/bootstrap.sh first." >&2
  exit 1
fi

cleanup() {
  # Kill the whole process group so Vite's child processes go too.
  [[ -n "${API_PID:-}" ]] && kill "$API_PID" 2>/dev/null || true
  [[ -n "${UI_PID:-}" ]] && kill "$UI_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

echo "==> Console API on http://localhost:8000"
.venv/bin/uvicorn main:app --app-dir backend/api --host 127.0.0.1 --port 8000 &
API_PID=$!

echo "==> Waiting for the API to become healthy"
for _ in $(seq 1 30); do
  if curl -sf http://localhost:8000/api/config >/dev/null 2>&1; then
    echo "    ready"
    break
  fi
  sleep 1
done

echo "==> UI on http://localhost:5173"
(cd frontend && npm run dev -- --host 127.0.0.1) &
UI_PID=$!

echo
echo "Open http://localhost:5173 — Ctrl-C to stop."
wait
