#!/usr/bin/env python3
# Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

"""Write terraform outputs into the env files the API and UI read.

Run after `terraform apply`:

    python3 scripts/write_env.py

Produces:
  .env.deploy            sourced by the console API (resource IDs, no secrets)
  frontend/.env.local    Vite config pointing the UI at the local API
  infra-outputs.json     the raw outputs, for reference and debugging
"""

import json
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
INFRA = REPO / "infra"

# terraform output name -> env var name
EXPORTS = {
    "region": "AWS_REGION",
    "runtime_arn": "RUNTIME_ARN",
    "registry_id": "REGISTRY_ID",
    "gateway_id": "GATEWAY_ID",
    "gateway_url": "GATEWAY_URL",
    "memory_id": "MEMORY_ID",
    "kyc_tools_lambda": "KYC_TOOLS_LAMBDA",
    # Model-plane wiring — surfaced to both the runtime container and the
    # console API so both sides can label which route handled a request.
    "guardrail_id": "GUARDRAIL_ID",
    "guardrail_version": "GUARDRAIL_VERSION",
}


def main() -> int:
    try:
        raw = subprocess.run(
            ["terraform", "output", "-json"],
            cwd=INFRA,
            capture_output=True,
            text=True,
            check=True,
        ).stdout
    except subprocess.CalledProcessError as exc:
        print(f"ERROR: terraform output failed: {exc.stderr}", file=sys.stderr)
        return 1
    except FileNotFoundError:
        print("ERROR: terraform not found on PATH", file=sys.stderr)
        return 1

    outputs = {key: value["value"] for key, value in json.loads(raw).items()}

    missing = [name for name in EXPORTS if name not in outputs]
    if missing:
        print(f"ERROR: terraform outputs missing: {missing}", file=sys.stderr)
        return 1

    lines = [
        "# Generated by scripts/write_env.py — do not edit.",
        "# Resource identifiers only; AWS credentials stay in .env.",
        "",
    ]
    for output_name, env_name in EXPORTS.items():
        lines.append(f"{env_name}={outputs[output_name]}")

    (REPO / ".env.deploy").write_text("\n".join(lines) + "\n")
    print(f"wrote {REPO / '.env.deploy'}")

    (REPO / "frontend" / ".env.local").write_text(
        "# Generated by scripts/write_env.py — do not edit.\n"
        "VITE_API_BASE=http://localhost:8000\n"
    )
    print(f"wrote {REPO / 'frontend' / '.env.local'}")

    # Write ONLY the allowlisted resource identifiers, never the full output
    # set. `terraform output -json` emits `sensitive` values (e.g. the console
    # password) in the clear, so dumping everything here would land a real
    # credential on disk — which is exactly what this file's docstring promises
    # it does not do.
    safe_outputs = {name: outputs[name] for name in EXPORTS}
    (REPO / "infra-outputs.json").write_text(
        json.dumps(safe_outputs, indent=2) + "\n"
    )
    print(f"wrote {REPO / 'infra-outputs.json'}")

    print("\nDeployed resources:")
    for output_name, env_name in EXPORTS.items():
        print(f"  {env_name:20s} {outputs[output_name]}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
