# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
import json
import logging
import os
import re
import subprocess
import urllib.error
import urllib.request
from typing import Optional, TypedDict

from container.lib.git_askpass import _create_askpass_script

# Re-exported so tests can patch ``container.tools.git_push_and_create_pr.
# _create_askpass_script`` the same way they patch it for git_clone.
__all__ = ["git_push_and_create_pr", "_create_askpass_script"]

logger = logging.getLogger(__name__)


class PushResult(TypedDict):
    pr_url: Optional[str]
    pushed: bool


def git_push_and_create_pr(
    work_dir: str,
    token: str,
    repo_url: str,
    target_branch: str,
    base_branch: str,
    task_description: str,
    job_id: str,
) -> PushResult:
    """Push branch and create GitHub pull request.

    Commits all changes, pushes with a 3-retry rebase loop, and creates
    a PR via the GitHub API. All network-touching git commands run with
    ``GIT_ASKPASS`` set to a short-lived script that echoes the caller's
    token so push/fetch can authenticate to GitHub.
    """
    subprocess.run(["git", "add", "-A"], cwd=work_dir, check=True, capture_output=True)

    diff = subprocess.run(
        ["git", "diff", "--cached", "--stat"],
        cwd=work_dir, capture_output=True, text=True,
    )
    if not diff.stdout.strip():
        return {"pr_url": None, "pushed": False}

    subprocess.run(
        ["git", "commit", "-m", f"opencode: {job_id}"],
        cwd=work_dir, check=True, capture_output=True,
    )

    # Push with 3-retry rebase logic — ALL remote ops use the askpass
    # script so push / fetch can authenticate.
    askpass_path = _create_askpass_script(token)
    try:
        git_env = {**os.environ, "GIT_ASKPASS": askpass_path}
        MAX_PUSH_RETRIES = 3
        for attempt in range(1, MAX_PUSH_RETRIES + 1):
            try:
                subprocess.run(
                    ["git", "push", "origin", target_branch],
                    cwd=work_dir, check=True, capture_output=True, env=git_env,
                )
                break  # Push succeeded
            except subprocess.CalledProcessError as push_err:
                if attempt == MAX_PUSH_RETRIES:
                    # Surface the underlying git stderr so callers see why
                    # the push actually failed, not just exit code 128.
                    stderr = (push_err.stderr or b"").decode("utf-8", errors="replace")
                    logger.error(
                        "git push failed on attempt %d/%d: %s",
                        attempt, MAX_PUSH_RETRIES, stderr[:500],
                    )
                    raise
                # Rebase on latest remote before retrying
                subprocess.run(
                    ["git", "fetch", "origin", base_branch],
                    cwd=work_dir, check=True, capture_output=True, env=git_env,
                )
                subprocess.run(
                    ["git", "rebase", f"origin/{base_branch}"],
                    cwd=work_dir, check=True, capture_output=True, env=git_env,
                )
    finally:
        if os.path.exists(askpass_path + ".token"):
            os.remove(askpass_path + ".token")
        if os.path.exists(askpass_path):
            os.remove(askpass_path)

    # Create PR via GitHub API
    match = re.search(r"github\.com/([^/]+)/([^/.]+)", repo_url)
    if not match:
        return {"pr_url": None, "pushed": True}

    owner, repo = match.group(1), match.group(2)
    pr_body = json.dumps({
        "title": task_description[:200],
        "body": f"Job: {job_id}\n\nGenerated by OpenCode on AgentCore.",
        "head": target_branch,
        "base": base_branch,
        "labels": ["opencode-generated"],
    })

    try:
        req = urllib.request.Request(
            f"https://api.github.com/repos/{owner}/{repo}/pulls",
            data=pr_body.encode(),
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        resp = urllib.request.urlopen(req)
        pr = json.loads(resp.read().decode())
        return {"pr_url": pr.get("html_url"), "pushed": True}
    except urllib.error.HTTPError as exc:
        body_snippet = ""
        try:
            body_snippet = exc.read().decode()[:200]
        except Exception:
            pass
        logger.warning(
            "GitHub API HTTP error %d creating PR for %s/%s: %s",
            exc.code, owner, repo, body_snippet,
        )
        return {"pr_url": None, "pushed": True}
    except urllib.error.URLError as exc:
        logger.warning(
            "GitHub API URL error creating PR for %s/%s: %s",
            owner, repo, exc.reason,
        )
        return {"pr_url": None, "pushed": True}
    except (json.JSONDecodeError, ValueError) as exc:
        logger.warning(
            "Failed to parse GitHub API response for %s/%s: %s",
            owner, repo, exc,
        )
        return {"pr_url": None, "pushed": True}
