#!/bin/bash
# Setup web-ui .env.local from deployment outputs
set -e

echo "🚀 Setting up Web UI environment..."

# Use AWS_REGION environment variable, fallback to us-east-1
REGION="${AWS_REGION:-us-east-1}"

# Get deployment ID
DEPLOYMENT_ID=$(node -p "require('./deployment-config.json').deploymentId" 2>/dev/null || echo "default")
STACK_NAME="AgentStack-${DEPLOYMENT_ID}"

# Parse flags
FORCE=false
MOCK_MODE=""
for arg in "$@"; do
    case $arg in
        --force) FORCE=true ;;
        --mock) MOCK_MODE="true" ;;
        --no-mock) MOCK_MODE="false" ;;
    esac
done

# Check if .env.local exists
if [[ -f "web-ui/.env.local" && "$FORCE" == "false" ]]; then
    echo "⚠️  web-ui/.env.local already exists"
    echo "   Run with --force to regenerate"
    exit 0
fi

# Get CDK outputs from CloudFormation
echo "📊 Querying ${STACK_NAME}..."
CDK_OUTPUTS=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" --query "Stacks[0].Outputs" --output json 2>/dev/null) || {
    echo "❌ Could not query ${STACK_NAME}. Deploy agent stack first."
    exit 1
}

# Parse CDK outputs
RUNTIME_ARN=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="MainRuntimeArn") | .OutputValue // empty')
RUNTIME_ID=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="MainRuntimeId") | .OutputValue // empty')
MEMORY_ID=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="MemoryId") | .OutputValue // empty')
GATEWAY_URL=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="GatewayUrl") | .OutputValue // empty')
GATEWAY_ID=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="GatewayId") | .OutputValue // empty')

# Get Visa Lambda proxy URL from VisaLambdaStack
VISA_STACK_NAME="VisaLambdaStack-${DEPLOYMENT_ID}"
echo "📊 Querying ${VISA_STACK_NAME}..."
VISA_OUTPUTS=$(aws cloudformation describe-stacks --stack-name "$VISA_STACK_NAME" --region "$REGION" --query "Stacks[0].Outputs" --output json 2>/dev/null) || {
    echo "⚠️  Could not query ${VISA_STACK_NAME}. Visa Lambda not deployed - using mock mode."
    VISA_PROXY_URL=""
}
if [[ -n "$VISA_OUTPUTS" && "$VISA_OUTPUTS" != "null" ]]; then
    VISA_PROXY_URL=$(echo "$VISA_OUTPUTS" | jq -r '.[] | select(.OutputKey=="VisaProxyApiUrl") | .OutputValue // empty')
    # Remove trailing slash if present
    VISA_PROXY_URL=${VISA_PROXY_URL%/}
fi

# Get Visa credentials from Secrets Manager
echo "📊 Fetching Visa credentials from Secrets Manager..."
VISA_API_KEY=$(aws secretsmanager get-secret-value --secret-id "visa/api-key" --query SecretString --output text 2>/dev/null) || VISA_API_KEY=""

# Read Amplify outputs
if [[ ! -f "amplify_outputs.json" ]]; then
    echo "❌ amplify_outputs.json not found. Deploy Amplify first."
    exit 1
fi

REGION=$(jq -r --arg default "$REGION" '.custom.region // $default' amplify_outputs.json)
USER_POOL_ID=$(jq -r '.auth.user_pool_id // empty' amplify_outputs.json)
USER_POOL_CLIENT_ID=$(jq -r '.auth.user_pool_client_id // empty' amplify_outputs.json)

# Validate required values
if [[ -z "$RUNTIME_ARN" || -z "$USER_POOL_ID" || -z "$USER_POOL_CLIENT_ID" ]]; then
    echo "❌ Missing required values. Ensure both stacks are deployed."
    exit 1
fi

# Determine mock mode: --mock flag overrides, otherwise default to false (real API)
if [[ "$MOCK_MODE" == "true" ]]; then
    FINAL_MOCK_MODE="true"
else
    FINAL_MOCK_MODE="false"
fi

# Generate .env.local
cat > web-ui/.env.local << EOF
# Auto-generated by setup-web-ui-env.sh
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# AWS Configuration
VITE_AWS_REGION=${REGION}

# Cognito Configuration
VITE_USER_POOL_ID=${USER_POOL_ID}
VITE_USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID}

# Agent Runtime Configuration
VITE_AGENT_RUNTIME_ARN=${RUNTIME_ARN}
VITE_AGENT_RUNTIME_ID=${RUNTIME_ID}
VITE_AGENT_ENDPOINT_NAME=DEFAULT

# Memory Configuration
VITE_MEMORY_ID=${MEMORY_ID}

# Gateway Configuration
VITE_GATEWAY_URL=${GATEWAY_URL}
VITE_GATEWAY_ID=${GATEWAY_ID}

# Visa Integration (default: no-mock when proxy available, use --mock to override)
VITE_VISA_MOCK_MODE=${FINAL_MOCK_MODE}
VISA_INTEGRATION_ENABLED=true
VITE_VISA_API_KEY=${VISA_API_KEY}
VITE_VISA_CLIENT_APP_ID=VICTestAccountTR
VITE_VISA_IFRAME_URL=https://sbx.vts.auth.visa.com
VITE_VISA_PROXY_URL=${VISA_PROXY_URL}
EOF

echo "✅ Created web-ui/.env.local"

if [[ -n "$VISA_PROXY_URL" ]]; then
    echo "✅ Visa proxy URL configured: $VISA_PROXY_URL"
    echo "   VITE_VISA_MOCK_MODE=false"
else
    echo "⚠️  Visa Lambda not deployed - using mock mode"
fi

if [[ -n "$VISA_API_KEY" ]]; then
    echo "✅ Visa API key loaded from Secrets Manager"
else
    echo "⚠️  Visa API key not found in Secrets Manager (visa/api-key)"
fi

echo ""
echo "Next: cd web-ui && npm run dev"
