import { SessionProvider } from "next-auth/react"

import type { Metadata } from "next";

import { CopilotKit } from "@copilotkit/react-core";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        <SessionProvider basePath="/auth">
          <CopilotKit runtimeUrl="/api/copilotkit" agent="strands_agent">
            {children}
          </CopilotKit>
        </SessionProvider>
      </body>
    </html>
  );
}
