import logging
from typing import Dict, Any
from datetime import datetime
from strands.tools import tool

logger = logging.getLogger(__name__)


@tool
def generate_marketing_report(
    research_findings: Dict[str, Any],
    report_title: str = "Marketing Research Report"
) -> str:
    """
    Generate a simple marketing research report as formatted text.
    
    Args:
        research_findings: Dictionary containing research data from various agents
        report_title: Title for the report
    
    Returns:
        Formatted text report ready for immediate use
    """
    try:
        logger.info("Generating marketing research report")
        
        # Generate report as simple formatted text
        date = datetime.now().strftime("%B %d, %Y")
        
        report = f"""# {report_title}

**Generated:** {date}

## Executive Summary

{_extract_summary(research_findings)}

## Key Findings

{_extract_findings(research_findings)}

## Recommendations

{_extract_recommendations(research_findings)}

## Supporting Data

{_extract_data_summary(research_findings)}

---
*Report generated by Marketing Research Agent*
"""
        
        return report
        
    except Exception as e:
        logger.error(f"Report generation failed: {e}")
        return f"Error generating report: {str(e)}"


def _extract_summary(findings: Dict[str, Any]) -> str:
    """Extract and format executive summary."""
    summary = "This marketing research analysis provides insights into market conditions, competitive landscape, and strategic opportunities."
    
    if findings.get('customer_data'):
        summary += " Customer analysis reveals behavioral patterns and segmentation opportunities."
    
    if findings.get('competitive_analysis'):
        summary += " Competitive intelligence indicates market positioning strategies."
    
    if findings.get('market_trends'):
        summary += " Market trend analysis shows growth opportunities and potential challenges."
    
    return summary


def _extract_findings(findings: Dict[str, Any]) -> str:
    """Extract and format key findings."""
    findings_text = ""
    
    # Research findings
    if findings.get('research_data'):
        findings_text += "- Market research indicates significant opportunities for growth and expansion\n"
    
    # Customer insights
    if findings.get('customer_data'):
        findings_text += "- Customer analysis reveals distinct behavioral patterns and preferences\n"
    
    # Competitive analysis
    if findings.get('competitive_analysis'):
        findings_text += "- Competitive landscape shows differentiation opportunities\n"
    
    # Analytics results
    if findings.get('analytics_results'):
        findings_text += "- Data analysis provides measurable insights for decision-making\n"
    
    if not findings_text:
        findings_text = "- Analysis provides comprehensive market insights\n- Strategic opportunities identified for business growth\n"
    
    return findings_text


def _extract_recommendations(findings: Dict[str, Any]) -> str:
    """Extract and format recommendations."""
    recommendations = """1. **Immediate Actions (0-30 days)**
   - Review current market positioning based on competitive analysis
   - Implement customer engagement optimizations identified in research

2. **Short-term Initiatives (30-90 days)**
   - Launch targeted campaigns based on customer insights
   - Develop response strategies for competitive threats

3. **Long-term Strategic Initiatives (90+ days)**
   - Pursue market expansion opportunities identified in analysis
   - Establish innovation processes based on market trends
"""
    
    return recommendations


def _extract_data_summary(findings: Dict[str, Any]) -> str:
    """Extract and format supporting data summary."""
    data_summary = ""
    
    for key, value in findings.items():
        if value:
            data_summary += f"- **{key.replace('_', ' ').title()}**: Analysis completed with actionable insights\n"
    
    if not data_summary:
        data_summary = "- Comprehensive market research conducted\n- Customer and competitive analysis completed\n"
    
    return data_summary