default_agent: au01
agents:
  au01:
    name: au01
    entrypoint: autogen_agent_hello_world.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::266239926753:role/agentcorerole
      account: '266239926753'
      region: us-west-2
      ecr_repository: null
      ecr_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: e24e9f90-2e8e-4b4e-a685-59df6883324b
    authorizer_configuration: null
    oauth_configuration:
      workload_name: workload-0fc046e8
