variable "name_prefix" {
  type        = string
  description = "Prefix applied to all resource names in this module."
}

variable "alb_fqdn" {
  type        = string
  description = "Public FQDN of the ALB (covered by an ACM-issued public cert). Gateway hits this over HTTPS for the OpenAPI target — must resolve and present a publicly-trusted chain."
}

variable "okta_discovery_url" {
  type        = string
  description = "Okta OIDC discovery URL (issuer + /.well-known/openid-configuration)."
}

variable "okta_audience" {
  type        = string
  description = "Audience the inbound JWT must carry. Also passed as the `audience` parameter on the outbound TOKEN_EXCHANGE call so the exchanged token targets the same backend."
}

variable "okta_allowed_clients" {
  type        = list(string)
  description = "Okta client IDs allowed by the Gateway customJWTAuthorizer (inbound)."
}

variable "okta_oauth2_provider_arn" {
  type        = string
  description = "ARN of the Okta OAuth2 credential provider (from the identity module). Used for outbound TOKEN_EXCHANGE."
}

variable "openapi_schema_path" {
  type        = string
  description = "Path to the OpenAPI 3.1 spec JSON file (relative to module root or absolute). Generated by `scripts/export_openapi.py`."
}

variable "policy_engine_mode" {
  type        = string
  description = "Policy engine enforcement mode: LOG_ONLY or ENFORCE. Start with LOG_ONLY, switch to ENFORCE once decisions in CloudWatch look right."
  default     = "LOG_ONLY"

  validation {
    condition     = contains(["LOG_ONLY", "ENFORCE"], var.policy_engine_mode)
    error_message = "policy_engine_mode must be LOG_ONLY or ENFORCE."
  }
}
