import { Stack } from 'aws-cdk-lib';
import { NagSuppressions } from 'cdk-nag';
import type { IConstruct } from 'constructs';

/**
 * cdk-nag suppressions — every one a stated argument, not a silencer.
 *
 * **The reasons are the point of this file.** A suppression list is where a security review either
 * gets honest or gets hollow: the failure mode is a wall of "N/A for this use case", which passes the
 * check and tells a reviewer nothing. So each entry below says what the rule is protecting against,
 * and why that threat either does not exist here or is answered by a different control.
 *
 * **What was fixed rather than suppressed**, because that ratio is the useful signal. 193 findings
 * became 3.
 *
 * | Finding | Action |
 * |---|---|
 * | `L1` — outdated Lambda runtimes (13) | **Fixed**: Python 3.13 → 3.14, Node 22 → 24 |
 * | `APIG1`/`APIG6` — no access or execution logging | **Fixed** on both stages. A comment in `mock-tmc-api.ts` *claimed* access logs were on; they were not |
 * | `CFR3` — no CloudFront access logging | **Fixed**, to a shared log bucket owned by `Storage` |
 * | `S1` — no S3 server access logs (3) | **Fixed** on the site, policy-docs and audit buckets |
 * | `VPC7` — no VPC flow logs | **Fixed** — and useful here specifically, since a `REJECT` record is how a missing endpoint stops being a mystery timeout |
 * | `IAM5` — wildcard resources (26) | **Acknowledged per finding**, so a *new* wildcard still fails the synth |
 * | `CFR4`, `APIG2`, `APIG3`, `APIG4`, `COG2`, `COG4`, `COG8`, `DDB3`, `CFR1`, `EC23`, `S1`(log bucket) | Acknowledged with reasons below |
 *
 * **All findings are now either fixed or suppressed with a reason — `cdk synth` exits 0.** Getting
 * there needed cdk-nag **v2** rather than v3: v3's `Validations.of().acknowledge()` cannot express a
 * finding id containing more than one `::`, which every `AwsSolutions-IAM4` id does (they embed a
 * policy ARN). v2 puts the finding in its own `appliesTo` field instead, which parses and matches.
 * See `bin/infra.ts` for the full account.
 *
 * One diagnostic trap worth recording: a **stale `cdk.out`** makes suppression changes look ineffective.
 * The findings reported were from a previous synth, which sent me chasing an API problem that was
 * already fixed. `rm -rf cdk.out` before concluding a suppression does not work.
 *
 * `cdk-nag` earned its place on the `L1` and `APIG1` findings alone: the first was a staleness nobody
 * had noticed, and the second contradicted a comment in this repo asserting the opposite.
 */
export function applyNagSuppressions(stack: Stack, logBucket: IConstruct): void {
  /**
   * **`IAM4` — managed policies on CDK-autogenerated roles, and `IAM5` — wildcard resources.**
   *
   * Both are suppressed per *finding* rather than per rule, which matters: a bare rule suppression
   * would also excuse any **future** managed policy or wildcard, so a new over-broad grant would land
   * silently. Naming each one means a new finding fails the check and has to be argued for.
   *
   * **`IAM4` argues against CDK's own grant model.** Preferring `grant*()` and autogenerated roles
   * over hand-written IAM is the idiom this stack follows throughout — and those roles attach exactly
   * the managed policies this rule flags. Satisfying it would mean bespoke
   * execution policies for 15 functions: more surface to get least privilege wrong, for no reduction
   * in reachable permissions. The API Gateway one is a *direct consequence* of enabling stage logging
   * to fix `APIG1`/`APIG6`.
   *
   * **What actually bounds this layer is not policy breadth.** Tenancy rests on
   * `dynamodb:LeadingKeys` against a per-request session-tagged role, Cedar at the gateway, and the
   * interceptor's header injection — which `verify_isolation.py` proves at seven independent layers.
   * A tool Lambda's execution role is deliberately broad *across* tenants, because it serves all of
   * them, and narrowed per request.
   */
  const MANAGED_POLICY_FINDINGS = [
    // Every Lambda writes its own logs.
    'Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
    // Added by CDK to the VPC-attached functions, for ENI management.
    'Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole',
    // Added by CDK when a REST API stage gets CloudWatch logging — i.e. by the APIG1/APIG6 fix.
    'Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs',
  ];
  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-IAM4',
        // **`appliesTo` rather than a bracketed id**, which is the v2 API's actual shape: an id
        // carrying `[finding]` is rejected with *"A finding must be suppressed using 'applies_to'"*.
        // The distinction matters — this list is what keeps the suppression narrow, so a *new*
        // managed policy on any role still fails the check instead of being silently covered.
        appliesTo: MANAGED_POLICY_FINDINGS,
        reason:
          'CDK attaches these managed policies to autogenerated service roles. This stack ' +
          'deliberately prefers autogenerated roles and grant() calls over hand-written ' +
          'policies, so satisfying this rule would mean bespoke execution policies for 15 ' +
          'functions — more surface to get least privilege wrong, for no reduction in reachable ' +
          'permissions. The API Gateway one is a direct consequence of enabling stage logging to ' +
          'fix APIG1/APIG6.',
      },
    ],
    true,
  );

  // **Built from the stack's own account and region, never written out.** cdk-nag matches an
  // `appliesTo` entry against the *resolved* finding, so a hardcoded account only matches in the
  // account it was copied from. Everywhere else the finding does not match, the suppression does
  // not apply, and `AwsSolutionsChecks` fails the synth — which blocks `cdk deploy` too, since a
  // failed validation stops both. Loud rather than silent, but it stops a reader's first deploy
  // dead for a reason that has nothing to do with them.
  const { account, region } = stack;

  const WILDCARD_FINDINGS = [
    // CDK grant-helper expansions. `grantReadWriteData` on a table with a GSI must include
    // `/index/*`; `grantRead` on a bucket expands to three `s3:*` action patterns.
    'Resource::<ConversationApiSessionsC0EA36F1.Arn>/index/*',
    'Resource::<StorageBookings2DC9463B.Arn>/index/*',
    'Resource::<StorageOffers92466CC7.Arn>/index/*',
    'Resource::<StoragePolicies9E59F43F.Arn>/index/*',
    'Resource::<StorageTenantConfig48276A08.Arn>/index/*',
    'Resource::<StorageTravelers8B8CF2BA.Arn>/index/*',
    'Resource::<StorageTrips3E0B3C13.Arn>/index/*',
    'Resource::<StoragePolicyDocs2C6B2455.Arn>/*',
    'Resource::<KnowledgeVectorBucket04B96F25.VectorBucketArn>/*',
    'Action::s3:GetBucket*',
    'Action::s3:GetObject*',
    'Action::s3:List*',
    // Amazon Location's standalone namespaces are account-level: there is no ARN to name.
    // Documented at the call site in `tools.ts`.
    'Resource::*',
    // AgentCore resources owned by the CLI's stack, which deploys *after* this one, so there is no
    // concrete ARN at synth time. Narrowed post-deploy by
    // `scripts/restrict_agentcore_endpoints.py`.
    `Resource::arn:aws:bedrock-agentcore:${region}:${account}:memory/*`,
    `Resource::arn:aws:bedrock-agentcore:${region}:${account}:runtime/*`,
    `Resource::arn:aws:bedrock-agentcore:${region}:${account}:runtime/*/*`,
    // This sample's own parameter prefix, read-only — narrower than the account's parameters, which
    // is the property that matters in a shared account.
    `Resource::arn:aws:ssm:${region}:${account}:parameter/multi-tenant-travel/agent/*`,
    // **`execute-api:Invoke` across the mock TMC's methods, which is the grant that closed a
    // critical hole rather than opened one.**
    //
    // The API is now `AWS_IAM`-authorized, so *something* must be allowed to sign — before this, it
    // was public and a tenant header alone returned full profile PII. The wildcard is
    // `/<stage>/<method>/<path>`, and narrowing it would mean enumerating every route each of nine
    // tools may call and keeping that list correct as the backend changes. A stale entry there fails
    // closed at runtime, inside a conversation, which is a worse failure than a broad grant to a
    // principal that is already trusted to assert a tenant.
    //
    // What bounds a tool is not this ARN: Cedar decides which tools a caller may invoke at all, and
    // `dynamodb:LeadingKeys` against the per-request session tag decides which rows it reaches.
    //
    // The ARN is hand-written at the grant site with a literal `aws` partition, because
    // `arnForExecuteApi()` leaves the partition as a token and cdk-nag cannot match an `appliesTo`
    // entry against a finding that still says `<AWS::Partition>`. Same reason the AgentCore entries
    // above spell it out.
    `Resource::arn:aws:execute-api:${region}:${account}:<MockTmcMockTmcRestApiFD9A7FF3>/*/*/*`,
  ];
  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-IAM5',
        appliesTo: WILDCARD_FINDINGS,
        reason:
          'Either a CDK grant-helper expansion (table /index/*, bucket /*, s3:Get*/List* patterns) ' +
          'or an API with no resource-level ARN to name: Amazon Location standalone namespaces are ' +
          'account-level, and AgentCore ARNs belong to a stack that deploys after this one ' +
          '(narrowed post-deploy by scripts/restrict_agentcore_endpoints.py). Tenancy is enforced ' +
          'by dynamodb:LeadingKeys on a per-request session-tagged role, Cedar at the gateway, and ' +
          'interceptor header injection — which verify_isolation.py proves at seven independent ' +
          'layers.',
      },
    ],
    true,
  );

  /**
   * `COG4` / `APIG4` — no Cognito authorizer, no API Gateway authorization. 26 findings.
   *
   * **This is the one suppression that reflects a deliberate architectural decision rather than a
   * cost or scope trade, so it is worth stating precisely.**
   *
   * The conversation API is a **BFF whose authentication is an httpOnly session cookie**, not a
   * bearer token. That is the whole security argument of the layer: the browser holds an opaque id,
   * the Cognito tokens live server-side in DynamoDB, and an XSS bug in the SPA finds nothing to steal.
   * A Cognito authorizer at the API Gateway would require the *browser* to hold and send a JWT —
   * exactly the design that was rejected, and the reason `main.py`'s module docstring exists.
   *
   * Every route verifies the session server-side (`_verified_bearer`, which calls Cognito's
   * `/oauth2/userInfo` before spending a runtime invoke), and the routes that are legitimately
   * unauthenticated are the OAuth entry points — `/auth/login` and `/auth/callback` — which cannot
   * require a session because their purpose is to establish one.
   *
   * The mock TMC API is `PRIVATE` with a resource policy conditioned on `aws:SourceVpce`, reachable
   * only from inside the VPC. It stands in for a travel platform that trusts a tenant header, and
   * establishing *who* the caller is happens above it, at the gateway and interceptor boundary.
   */
  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-COG4',
        reason:
          'The conversation API authenticates with an httpOnly session cookie verified server-side, ' +
          'deliberately not a browser-held JWT — a Cognito authorizer would require the SPA to hold ' +
          'a token, which is the design this BFF exists to avoid. The mock TMC API is PRIVATE, ' +
          'reachable only via a VPC endpoint, and trusts an injected tenant header by design.',
      },
    ],
    true,
  );

  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-APIG4',
        reason:
          'Same as COG4: session-cookie authentication is enforced in the application on every ' +
          'route, and the only unauthenticated routes are the OAuth entry points, which cannot ' +
          'require a session because their job is to create one. The backend API is VPC-private.',
      },
    ],
    true,
  );

  /**
   * `APIG2` — no request validation.
   *
   * Request validation means a JSON Schema model per method, enforced at the gateway. Both APIs here
   * are **proxy integrations** (`{proxy+}` to FastAPI; a raw ASGI app behind the Lambda Web Adapter),
   * so there are no per-method models to validate against — the gateway does not know the routes.
   *
   * Validation happens where the shape is actually known: FastAPI's pydantic models in the backend,
   * and explicit checks in the BFF (session id length, empty message, the closed action registry,
   * conversation-id minimum). The registry in `actions.py` is the strongest of these and could not be
   * expressed as a gateway model at all — it validates against an enum shared with the tool layer.
   */
  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-APIG2',
        reason:
          'Both APIs are proxy integrations, so the gateway has no per-method models to validate. ' +
          'Input validation lives where the shape is known: pydantic in the FastAPI backend, and ' +
          'explicit checks in the BFF (session-id length, empty message, and the closed action ' +
          'registry, which validates against an enum shared with the tool layer).',
      },
    ],
    true,
  );

  /**
   * `DDB3` — no point-in-time recovery. 7 findings, one per table.
   *
   * **PITR on these tables would be incoherent rather than merely unnecessary.** Every table carries
   * `removalPolicy: DESTROY` because a sample must leave nothing behind, and their contents are
   * *regenerable fixtures* — `seed.load` rebuilds them deterministically. Paying for continuous
   * backups of data that a script reproduces exactly, on tables designed to be deleted, is the kind
   * of box-ticking that makes a compliance list less credible.
   *
   * **What a real deployment should do is stated in `storage.ts` itself** ("Production would use
   * RETAIN and point-in-time recovery"), which is the honest form for a sample: show the demo-scale
   * choice, name the production one.
   *
   * The session table is a different argument and lands at the same place: its rows are short-lived by
   * design (TTL on `expires_at`), so a point-in-time restore would recover sessions that had already
   * legitimately expired.
   */
  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-DDB3',
        reason:
          'Table contents are regenerable fixtures (seed.load rebuilds them deterministically) on ' +
          'tables with removalPolicy DESTROY, so continuous backups protect nothing recoverable. ' +
          'The session table holds deliberately short-lived rows expired by TTL. storage.ts states ' +
          'that a production deployment would use RETAIN plus PITR.',
      },
    ],
    true,
  );

  /**
   * `COG2` — no MFA, and `COG8` — not on the Cognito Plus feature plan.
   *
   * **These are fixture logins, and MFA would make the sample unrunnable.** The three seeded personas
   * exist so a reader can sign in as a globex traveller and then an initech traveller and watch the
   * same question get two answers. Requiring a TOTP enrolment per persona means every reader who
   * clones this repo has to enrol three authenticators before the point of the sample is visible.
   *
   * Worth being clear about the limit of that argument: **MFA is the right answer for any real
   * deployment of this pattern**, and the pool is configured so enabling it is a property change
   * rather than a redesign. It is suppressed because these are throwaway identities holding fixture
   * data, not because MFA is optional for corporate travel.
   *
   * `COG8`'s Plus tier buys threat protection (compromised-credential detection, adaptive auth) at a
   * per-MAU premium. For seeded fixture logins there are no credentials to find compromised.
   *
   * One thing the pool *does* enforce, and which matters more here than either: `custom:tenant_id`
   * and `custom:traveler_id` are **immutable**, so a traveller cannot edit their own tenancy.
   */
  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-COG2',
        reason:
          'Seeded fixture personas for a sample; per-persona TOTP enrolment would mean every reader ' +
          'enrols three authenticators before the tenancy contrast is visible. MFA is the correct ' +
          'setting for a real deployment and is a property change away. The pool enforces what matters ' +
          'most here: tenant_id and traveler_id are immutable custom attributes.',
      },
    ],
    true,
  );

  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-COG8',
        reason:
          'The Plus feature plan adds threat protection priced per MAU. With a fixed set of demo ' +
          'logins there are no user credentials that could be found compromised, so this is cost ' +
          'without a corresponding risk reduction.',
      },
    ],
    true,
  );

  /**
   * `CFR1` — geo restrictions.
   *
   * A warning rather than an error, and correctly a judgement call: the rule cannot know a
   * distribution's intended audience. This one is a demo meant to be opened by AWS staff and
   * customers anywhere, so a country allowlist would block legitimate viewers to no security end.
   *
   * Abuse is bounded by API Gateway stage throttling, which is always on and origin-independent —
   * **stated that way rather than crediting the WAF**, because the web ACL is now opt-in (`--waf`)
   * and a suppression whose justification disappears with a flag is not a justification.
   */
  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-CFR1',
        reason:
          'A globally-presented demo has no country allowlist that would not block legitimate ' +
          'viewers. Abuse is bounded by API Gateway stage throttling, which is always on and ' +
          'origin-independent; the WAF adds managed rules on top when enabled with --waf.',
      },
    ],
    true,
  );

  /**
   * `S1` on the log bucket only — a bucket cannot log to itself.
   *
   * Scoped to the one resource rather than suppressed stack-wide, because the site bucket *does* now
   * have access logging and should keep being checked for it. S3 rejects a bucket whose access-log
   * destination is itself, and pointing it at a second log bucket only moves the question.
   */
  // **Scoped to the log bucket, not the stack.** `addResourceSuppressions` keeps the site, policy-docs
  // and audit buckets under the rule — a stack-wide suppression would have quietly excused all four,
  // which is the opposite of what the reason above claims.
  NagSuppressions.addResourceSuppressions(logBucket, [
    {
      id: 'AwsSolutions-S1',
      reason:
        'This is the access-log destination. S3 refuses a bucket that logs to itself, and a ' +
        'second log bucket would only relocate the same finding. Scoped to this construct so the ' +
        'site bucket continues to be checked.',
    },
  ]);

  /**
   * `CFR4` — TLS floor on viewer connections. **The one finding that cannot be fixed at this layer.**
   *
   * `minimumProtocolVersion` only takes effect with a *custom* certificate. This distribution uses the
   * default `*.cloudfront.net` domain — a sample cannot assume the reader owns a domain, and asking
   * for one to clear a lint finding is the wrong trade — and CloudFront fixes that domain's TLS policy
   * itself. So the property is set in
   * `frontend-hosting.ts` (so a future custom domain inherits the right floor) and is inert today.
   *
   * The practical exposure is nil: the `*.cloudfront.net` policy does not negotiate SSLv3, and every
   * browser that can run a React SPA negotiates TLS 1.2 or better. The finding is about what the
   * *configuration* permits in principle, not what any real client will use.
   */
  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-CFR4',
        reason:
          'minimumProtocolVersion applies only with a custom certificate, and this sample uses the ' +
          'AWS-managed *.cloudfront.net domain — so CloudFront owns that domain TLS policy and ' +
          'the property is inert. It is set anyway so a future custom domain inherits TLS 1.2. No ' +
          'real client negotiates below TLS 1.2 against that domain.',
      },
    ],
    true,
  );

  /**
   * `APIG3` — no WAFv2 ACL on the REST API stage. **Fixed in substance, not in the shape the rule
   * looks for.**
   *
   * When enabled, the ACL is attached to the CloudFront distribution, which is the *only* intended
   * public entrance: the conversation API is reachable at `/v1/*` through that distribution, and the
   * mock TMC API is now `AWS_IAM`-authorized (and `PRIVATE` too under `--private`). A second regional
   * ACL per stage would bill per rule to inspect traffic that either already passed the edge ACL or
   * cannot be called without a signature.
   *
   * **The ACL is opt-in, so the honest version of this suppression does not depend on it.** What
   * always holds: the mock TMC refuses an unsigned caller, and the conversation API's execute-api
   * hostname reaches an unauthenticated 401 because the session cookie is `SameSite=Strict` and
   * scoped to the CloudFront origin. Stage throttling is always on and bounds volume. What `--waf`
   * adds on top is managed rule sets and edge rate limiting.
   */
  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-APIG3',
        reason:
          'A regional ACL per stage would bill per rule to inspect traffic that is already bounded: ' +
          'the mock TMC is AWS_IAM-authorized so an unsigned caller never reaches it, the ' +
          'conversation API is served through CloudFront and its direct hostname reaches a 401 ' +
          'because the session cookie is SameSite=Strict, and stage throttling is always on. The ' +
          'edge ACL adds managed rules when enabled with --waf.',
      },
    ],
    true,
  );

  /**
   * `EC23` — the rule threw during validation rather than finding anything.
   *
   * cdk-nag's own message says so: *"Rule threw an error during validation. This is generally caused
   * by a parameter referencing an intrinsic function."* The security group rule it inspects references
   * the compute security group by `Fn::GetAtt`, which the rule cannot resolve at synth time.
   *
   * **Acknowledged as a tool limitation, and the underlying property is verified elsewhere instead** —
   * `scripts/verify_network.py` check B asserts against the deployed route tables that no subnet has
   * a route to an internet or NAT gateway, which is a stronger statement than the rule was attempting.
   */
  NagSuppressions.addStackSuppressions(
    stack,
    [
      {
        id: 'AwsSolutions-EC23',
        reason:
          'The rule errors rather than reporting: it cannot resolve a security group reference that is ' +
          'an Fn::GetAtt at synth time. The property it checks is verified against deployed state by ' +
          'scripts/verify_network.py (no route to an internet or NAT gateway from any subnet).',
      },
    ],
    true,
  );
}
