# Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

"""Specialist agent skill definitions.

Each specialist module declares one `Skill`, which is the single source of truth
for that agent's identity: its name, the Gateway tools it may call, its system
prompt, and its catalog documentation.

Two consumers read these, which is the point:

  backend/agent/orchestrator.py   builds the agent and scopes its tools
  scripts/seed_registry.py        registers the AGENT_SKILLS record

Previously each restated the other's facts — the skill name and the tool list
were written out separately in the orchestrator and in the seed script, so
renaming a skill or rescoping a specialist left the Registry describing a system
that no longer existed. For a governance catalog that is the failure mode that
matters, so the frontmatter name and the "Tools required" section are now
*generated* from these fields rather than hand-maintained.

This module deliberately imports nothing beyond the standard library. The seed
script runs outside the agent's container and must be able to import a Skill
without pulling in strands, boto3, or the MCP client.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class Skill:
    """One specialist's complete definition.

    Attributes:
        name: Registry record name, and the `name:` in the skill's frontmatter.
            Lowercase and hyphenated, e.g. "aml-compliance-screening".
        summary: One-line `description:` for the frontmatter — what the skill
            does, in a sentence a human scanning the catalog can act on.
        record_description: The Registry record's own `description` field, shown
            in the console's catalog list.
        tools: Gateway tool names this specialist may call. The orchestrator
            filters the Gateway's advertised tools down to exactly these, and
            the generated markdown documents them.
        system_prompt: The prompt handed to the model.
        body: Skill markdown *without* frontmatter and without a "Tools
            required" section — both are generated by `to_markdown()`.
    """

    name: str
    summary: str
    record_description: str
    tools: tuple[str, ...]
    system_prompt: str
    body: str

    def to_markdown(self) -> str:
        """Render the SKILL.md content for this skill's Registry record.

        The service rejects an AGENT_SKILLS descriptor whose content does not
        open with `---`-delimited frontmatter, so the frontmatter is emitted
        first and the name is taken from `self.name` — it cannot disagree with
        the record name.

        The "Tools required" section is likewise derived from `self.tools`, so
        the catalog always documents the tools the orchestrator actually grants.
        """
        tool_list = ", ".join(f"`{tool}`" for tool in self.tools)
        return (
            f"---\n"
            f"name: {self.name}\n"
            f"description: {self.summary}\n"
            f"---\n"
            f"\n"
            f"{self.body.strip()}\n"
            f"\n"
            f"## Tools required\n"
            f"\n"
            f"{tool_list} (via the kyc-gateway MCP server)\n"
        )

    def to_registry_record(self) -> dict:
        """Build the CreateRegistryRecord payload for this skill."""
        return {
            "name": self.name,
            "description": self.record_description,
            "descriptorType": "AGENT_SKILLS",
            "descriptors": {
                "agentSkills": {"skillMd": {"inlineContent": self.to_markdown()}}
            },
        }
